# Generated by Django 5.2.6 on 2025-09-21 22:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_address', models.CharField(max_length=255)),
                ('delivery_address', models.CharField(max_length=255)),
                ('package_description', models.TextField()),
                ('preferred_vehicle', models.CharField(choices=[('bike', 'Bike (₦1,500)'), ('keke', 'Keke (₦2,500)'), ('van', 'Van (schedule a call: 07074423164)'), ('truck', 'Truck (schedule a call: 07074423164)')], max_length=20)),
                ('delivery_date', models.DateField()),
                ('delivery_time', models.TimeField()),
                ('special_instructions', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Transit', 'In Transit'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
