# Generated by Django 5.2.6 on 2025-10-16 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_region',
            field=models.CharField(choices=[('Igoli', 'Igoli'), ('Okuku', 'Okuku'), ('Abakpa', 'Abakpa'), ('Abouchiche', 'Abouchiche')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_region',
            field=models.CharField(choices=[('Igoli', 'Igoli'), ('Okuku', 'Okuku'), ('Abakpa', 'Abakpa'), ('Abouchiche', 'Abouchiche')], max_length=20, null=True),
        ),
    ]
