# Generated by Django 5.2.6 on 2025-10-24 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_delivery_amount_order_delivery_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='preferred_vehicle',
            field=models.CharField(choices=[('bike', 'Bike'), ('keke', 'Keke'), ('van', 'Van'), ('truck', 'Truck')], max_length=20),
        ),
        migrations.CreateModel(
            name='OrderLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location', to='orders.order')),
            ],
        ),
    ]
