# Generated by Django 5.2.6 on 2025-10-31 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
    ]
